version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  visualizer:
    image: ailuropoda/fastlane-visualizer:latest
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_ENDPOINT=elasticsearch:9200

  filebeat:
    build: filebeat/
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
      - ./filebeat/config/fastlane_elastic.template.json:/usr/share/filebeat/config/fastlane_elastic.template.json
      - /tmp/tshark/data/:/usr/share/filebeat/data/
    environment:
      - ELHOST=elasticsearch:9200
      - FILEPATH=/usr/share/filebeat/data/logs.data
      - ELTEMPLATE=fastlane
      - ELTEMPLATE_PATH=/usr/share/filebeat/config/fastlane_elastic.template.json
      - ELPROTOCOL=http
    depends_on:
      - elasticsearch
